In [1]:
!pip install pandas numpy openpyxl sqlalchemy pymysql

Requirement already satisfied: pandas in C:\Users\ronit\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in C:\Users\ronit\anaconda3\Lib\site-packages (2.4.6)
Requirement already satisfied: openpyxl in C:\Users\ronit\anaconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: sqlalchemy in C:\Users\ronit\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: pymysql in C:\Users\ronit\anaconda3\Lib\site-packages (1.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ronit\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ronit\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: et_xmlfile in C:\Users\ronit\anaconda3\Lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: greenlet>=1 in C:\Users\ronit\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\ronit\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\Users\ronit\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
# step 1: import libraries
import pandas as pd
import numpy as np

In [3]:
#step 2: Load Dataset
df=pd.read_excel(r'C:\Users\ronit\Downloads\End to End Project\End to End Project\Ecommerce_Unclean_Project.xlsx')

In [4]:
# step 3: Explore the  dataset
# View top five record 
df.head(5)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [5]:
# step 4: Data information  
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    str
 1   Order_Date     524 non-null    str
 2   Customer_Name  524 non-null    str
 3   Email          524 non-null    str
 4   Phone          502 non-null    float64
 5   City           524 non-null    str
 6   State          524 non-null    str
 7   Product        524 non-null    str
 8   Category       524 non-null    str
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    str
 13  Order_Status   524 non-null    str
 14  Delivery_Date  503 non-null    str
dtypes: float64(3), object(1), str(11)
memory usage: 107.3+ KB

In [6]:
# Step 5:Statistical summary  
df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [7]:
# step 6:Data shape  
df.shape

(524, 15)

In [8]:
# Step 7: Checking Missing values  
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [9]:
# step 8: Check duplicate records 
df.duplicated().sum()

np.int64(11)

In [10]:
# step 9: Remove duplicate values     
df.drop_duplicates(inplace=True)

In [11]:
# Step 10: Again check duplicates
df.duplicated().sum()

np.int64(0)

In [12]:
# Step 11: Replace invalid values
# Replace common invalid values with NaN 
df.replace(['N/A','Null',' '],np.nan,inplace=True)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,NaN,Wallet,Cancelled,07-04-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,ORD1608,17-02-2025,Rahul,rahul71@gmail.com,9.789375e+09,Lucknow,UP,Mouse,Electronics,4.0,9999.0,NaN,Card,Returned,27-02-2025
520,ORD1609,2025/03/21,Rahul,rahul99@gmail.com,9.552650e+09,Mumbai,Maharashtra,Bottle,Home,2.0,1499.0,NaN,Wallet,Pending,28-03-2025
521,ORD1610,10-04-2025,Rohit,rohit96@gmail.com,9.700117e+09,Jaipur,Rajasthan,Mouse,Electronics,1.0,NaN,NaN,NetBanking,Delivered,16-04-2025
522,ORD1611,11-01-2025,Neha,neha22@gmail.com,9.580304e+09,Jaipur,Rajasthan,Chair,Furniture,3.0,999.0,NaN,COD,Pending,16-01-2025
523,ORD1612,03-03-2025,Vikas,vikas46@gmail.com,9.551158e+09,Jaipur,Rajasthan,Shoes,Fashion,3.0,999.0,5,COD,Cancelled,09-03-2025

In [13]:
# step 12:Remove extra blank rows
df=df.dropna(how='all')

In [14]:
# step 13:Remove extra blank columns
df=df.dropna(axis=1,how='all')

In [15]:
# step 14:Remove extra spaces  of text/data values
df=df.map(lambda x: x.strip() if isinstance(x,str) else x)

In [16]:
# step 15: Standardize text formet 
# Convert text into proper Case.
df['Customer_Name']=df['Customer_Name'].str.title()
df['City']=df['City'].str.title()
df['State']=df['State'].str.title()
df['Product']=df['Product'].str.title()
df['Category']=df['Category'].str.title()
df['Order_Status']=df['Order_Status'].str.title()

In [18]:
# Step 16: Volidate email addresses
#  Keep only valid email records 
df=df[df['Email'].str.contains('@',na=False)]

In [19]:
# step 17: Convert date columns
df['Order_Date']=pd.to_datetime(df['Order_Date'],dayfirst=True,errors='coerce')
df['Delivery_Date']=pd.to_datetime(df['Delivery_Date'],dayfirst=True,errors='coerce')

In [20]:
# step 18: Convert Numeric Columns
cols=['Qty','Unit_Price','Discount']
for c in cols:
    df[c]=pd.to_numeric(df[c],errors='coerce')

In [21]:
# step 19: Remove Invalid id Quantity.
# Remove records having negative or zeros quantity
df=df[df['Qty']>0]

In [22]:
# step 20: fill missing values 
df['Discount']=df['Discount'].fillna(0)
df['Phone']=df['Phone'].fillna('unknowm')
df['Delivery_Date']=df['Delivery_Date'].fillna(df['Order_Date'])

In [23]:
# step 21 frature engineering
#total sales
df['Sales']=df['Qty']*df['Unit_Price']

In [24]:
df.head(2)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-02-09,24995.0

In [25]:
# step 22: net amount
df['NET_Amount']=df['Sales']-(df['Sales']*df['Discount']/100)

In [26]:
df.head(2)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,NET_Amount
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,7996.0,7996.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-02-09,24995.0,19996.0

In [29]:
# step 23: profit(Example:20%)
df['Profit']=(df['NET_Amount']*0.20).round(2)

In [30]:
df.head(2)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,NET_Amount,Profit
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,7996.0,7996.0,1599.2
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-02-09,24995.0,19996.0,3999.2

In [31]:
#step 24:order month find by order date 
df['Month']=df['Order_Date'].dt.month_name()

In [32]:
df.head(2)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,NET_Amount,Profit,Month
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,7996.0,7996.0,1599.2,June
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-02-09,24995.0,19996.0,3999.2,February

In [33]:
#step 25:order month find by order year
df['Year']=df['Order_Date'].dt.year

In [34]:
df.head(2)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,NET_Amount,Profit,Month,Year
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,1999.0,0.0,UPI,Pending,2025-07-03,7996.0,7996.0,1599.2,June,2025.0
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20.0,Card,Pending,2025-02-09,24995.0,19996.0,3999.2,February,2025.0

In [35]:
#step 24:order month find by order weekday 
df['weak_day']=df['Order_Date'].dt.day_name()

In [36]:
df.head(2)

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,...,Discount,Payment_Mode,Order_Status,Delivery_Date,Sales,NET_Amount,Profit,Month,Year,weak_day
0,ORD1002,2025-06-30,Neha,neha82@gmail.com,9829008196.0,Delhi,Delhi,Chair,Furniture,4.0,...,0.0,UPI,Pending,2025-07-03,7996.0,7996.0,1599.2,June,2025.0,Monday
1,ORD1003,2025-02-03,Rohit,rohit45@gmail.com,9280491167.0,Pune,Maharashtra,Watch,Fashion,5.0,...,20.0,Card,Pending,2025-02-09,24995.0,19996.0,3999.2,February,2025.0,Monday

In [37]:
df.info()

<class 'pandas.DataFrame'>
Index: 380 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       374 non-null    str
 1   Order_Date     333 non-null    datetime64[us]
 2   Customer_Name  380 non-null    str
 3   Email          380 non-null    str
 4   Phone          380 non-null    object
 5   City           380 non-null    str
 6   State          380 non-null    str
 7   Product        380 non-null    str
 8   Category       380 non-null    str
 9   Qty            380 non-null    float64
 10  Unit_Price     343 non-null    float64
 11  Discount       380 non-null    float64
 12  Payment_Mode   380 non-null    str
 13  Order_Status   380 non-null    str
 14  Delivery_Date  378 non-null    datetime64[us]
 15  Sales          343 non-null    float64
 16  NET_Amount     343 non-null    float64
 17  Profit         343 non-null    float64
 18  Month          333 non-null    str
 19  Year           333 non-null    float64
 20  weak_day       333 non-null    str
dtypes: datetime64[us](2), float64(7), object(1), str(11)
memory usage: 95.8+ KB

In [38]:
df.shape

(380, 21)

In [39]:
df.isnull().sum()

Order_ID          6
Order_Date       47
Customer_Name     0
Email             0
Phone             0
City              0
State             0
Product           0
Category          0
Qty               0
Unit_Price       37
Discount          0
Payment_Mode      0
Order_Status      0
Delivery_Date     2
Sales            37
NET_Amount       37
Profit           37
Month            47
Year             47
weak_day         47
dtype: int64

In [40]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date,Sales,NET_Amount,Profit,Year
count,333,380.000000,343.000000,380.000000,378,343.000000,343.000000,343.000000,333.0
mean,2025-04-02 17:35:08.108108,3.328947,3252.352770,7.802632,2025-04-10 08:41:54.285714,11103.664723,10249.073324,2049.814665,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.000000,2025-01-05 00:00:00,499.000000,399.200000,79.840000,2025.0
25%,2025-02-14 00:00:00,2.000000,999.000000,0.000000,2025-02-23 00:00:00,2599.000000,2398.400000,479.680000,2025.0
50%,2025-04-05 00:00:00,3.000000,1999.000000,5.000000,2025-04-13 00:00:00,5997.000000,5996.000000,1199.200000,2025.0
75%,2025-05-16 00:00:00,5.000000,4999.000000,15.000000,2025-05-25 00:00:00,12995.000000,12995.000000,2599.000000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,20.000000,2025-07-08 00:00:00,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,1.458196,3026.092014,7.881075,NaN,12194.528486,11506.169779,2301.233956,0.0

In [41]:
df.columns= df.columns.str.lower()

In [42]:
df.columns=(
    df.columns
    .str.lower()
    .str.strip()
    .str.replace(" ","_"))

In [43]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in C:\Users\ronit\anaconda3\Lib\site-packages (2.9.13)

In [44]:
# step to export data 
df.to_csv('Clean_Date.casv',index=False)

In [45]:
# import data into sql
from sqlalchemy import create_engine
engine=create_engine('postgresql+psycopg2://postgres:494949ronit@localhost:5432/ecommerce')

In [46]:
# export datafrme to postgresql
df.to_sql(
    name='orders',con=engine,if_exists='replace',index=False
)

380